# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 19:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('company_name', models.CharField(blank=True, max_length=128)),
                ('domain_name', models.CharField(help_text='Domain name you wish to have, e.g: company.demoti.me', max_length=128)),
                ('email_address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('team_size', models.CharField(choices=[('1-10', '1-10'), ('10-30', '10-30'), ('30-50', '30-50'), ('50+', '50+')], max_length=24)),
            ],
            options={
                'abstract': False,
                'ordering': ['-created'],
            },
        ),
    ]
