# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pannier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='contacted',
            field=models.BooleanField(default=False),
        ),
    ]
